# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable line length rule
MD013: false

# Allow inline HTML
MD033: false

# Allow duplicate headers
MD024:
  allow_different_nesting: true

# Allow trailing punctuation in headers
MD026: false

# Allow bare URLs
MD034: false

# Allow ordered list style inconsistencies
MD029: false

# Allow fenced code blocks without language
MD040: false
